version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: deha_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/html
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deha_php
    volumes:
      - ./app:/var/www/html

  mysql:
    image: mysql:8.0
    container_name: deha_mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: deha_db
      MYSQL_USER: deha
      MYSQL_PASSWORD: deha_pass
    ports:
      - "33060:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
